### PR TITLE
Feat/tc cypress

### LINKED ISSUE #15: Some Cypress testing

### LINKED ISSUE #26: refine second flower and collisions

### LINKED ISSUE #32: Plants grow

### LINKED ISSUE #33: Delete button styling

### LINKED ISSUE #34: Plants should not reach for God

### PR DESCRIPTION
**Pull request by tconey23**
# Summary  

Adds Cypress testing for Canvas
Adds refined flowers
Adds delete flower button
Bug fixes on flower rendering

# Questions (if needed) 

image

# To do 

Need to resolve merge conflicts!

### CODE REVIEW

**Comment by cOdeBedient** [comment]
We can work to resolve eslint warnings in future iterations, but I am skeptical about some of the suggested changes...

**Comment by edwin-chalmers** [comment]
Don't forget to deploy!

**Comment by cOdeBedient** [comment]
I absolutely love the MeshWobbleMaterial. I wonder if we could use that with the text?

**Comment by edwin-chalmers** [comment]
Needs more wiggles :(

**Pull request merged**
